apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: airnes-api
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: airnes-ecommerce-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: airnes-api
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: airnes-ecommerce-api
  ports:
    - port: 9000
      targetPort: 9000
