apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app.kubernetes.io/name: airnes-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce-airnes-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airnes-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ecommerce-airnes-site
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airnes-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: ecommerce-airnes-site
    spec:
      containers:
        - name: api
          image: tsiang/airnes_k8s_api:latest
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
