//import { url } from "inspector";

const ProductData = [
  {
    id: "0",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "1",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "2",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "3",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "4",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "5",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
  {
    id: "6",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "7",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "8",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "9",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "10",
    name: "Chaise en bois",
    categorie: "chaise",
    prix: "95",
    stock: "2",
    description:
      "chaise en bois :   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois,tissus",
    img: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",

    img1: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "11",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "12",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "13",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "14",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "15",
    name: "table 6 personnes",
    categorie: "table",
    prix: "500",
    stock: "4",
    description:
      "table blanche 6 personnes exetensibles jusqu'a 10 personnes : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.emob-meubles.fr/media/catalog/product/cache/47315658861446b438ceea760f29ab26/5/d/5d3d8512_b1c8_4317_b7b4_5fee180c914e_2eca.jpg",
    img1: "https://royal-bois.com/cdn/shop/files/table-a-manger-blanc-laque-50712395546956.jpg?v=1692433374",
    img2: "https://www.so-inside.com/2243-medium_default/table-a-manger-baroque-blanche-lori.jpg",
  },
  {
    id: "16",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "17",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "18",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "19",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "20",
    name: "canapé 3 places",
    categorie: "canapé",
    prix: "1500",
    stock: "7",
    description:
      "canapé 3 places qui se transforme en lit : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "cuire",
    img: "https://i0.wp.com/www.balmaison.com/wp-content/uploads/2020/02/Blanche-canap%C3%A9-3-places-beige-9.jpg?fit=1500%2C843&ssl=1",
    img1: "https://cdn.happy-garden.fr/_hgfr_/20584-medium_default/canape-3-places-convertible-en-velours-vert-eucalyptus-oscar.jpg",
    img2: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
  },
  {
    id: "21",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "22",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "23",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "24",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "25",
    name: "table basse en verre",
    categorie: "table basse",
    prix: "500",
    stock: "10",
    description:
      "table basse en verre avec bois:  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem. ",
    materieaux: "verre,bois",
    img: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
    img1: "https://cdn.maisonetstyles.com/content/cache/produit/1000x1000/1343139_1_L.jpg",
    img2: "https://kasbah-design.com/wp-content/uploads/2023/01/table-basse-thara-travertin-detail-3-kasbah-design-marrakech.jpg",
  },
  {
    id: "26",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "27",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "28",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "29",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "30",
    name: "buffet",
    categorie: "buffet",
    prix: "900",
    stock: "9",
    description:
      "buffet en bois: Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img1: "https://www.robindesbois.com/9605-large_default/mathilde-buffet-seventy.jpg",
    img2: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
  },
  {
    id: "31",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
  {
    id: "32",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
  {
    id: "33",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
  {
    id: "34",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
  {
    id: "35",
    name: "table gigogne",
    categorie: "table gigogne",
    prix: "500",
    stock: "7",
    description:
      " ensemble de 3 tables gigognes en hetre : Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia id molestias eaque sint dolor officiis numquam tempora labore et facilis vel, sed sunt quo! Eligendi quo nostrum nemo minus dolorem.",
    materieaux: "bois",
    img: "https://www.mmhome.fr/media/catalog/product/cache/1/image/480x407/85e4522595efc69f496374d01ef2bf13/t/a/table_basse_gigogne_industrielle_bois_et_m_tal_jersey_6_-mmhome.fr.jpg",
    img1: "https://www.brindouest.com/wp-content/uploads/2017/10/chaise-moderne-en-bois-massif.jpg",
    img2: "https://www.novomeuble.com/12648-thickbox_default/chaise-blanche-bois.jpg",
  },
];
export default ProductData;
